# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daddypunmaster3000', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_jokes', models.CharField(default=b'[]', max_length=512)),
            ],
        ),
    ]
